In [1]:
import pandas as pd

df_list = pd.read_html('https://fbref.com/en/squads/53a2f082/2024-2025/all_comps/Real-Madrid-Stats-All-Competitions', attrs={"id":"stats_standard_combined"})

In [2]:
player_stats_df = df_list[0]
print(player_stats_df.head())

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0  Federico Valverde             uy URU              MF,DF             26-178
1    Antonio Rüdiger             de GER                 DF             31-319
2      Kylian Mbappé             fr FRA                 FW             26-027
3   Thibaut Courtois             be BEL                 GK             32-250
4    Jude Bellingham            eng ENG                 MF             21-201

  Unnamed: 4_level_0 Playing Time               Performance       ...  \
                  MP       Starts     Min   90s         Gls  Ast  ...
0                 29           29  2444.0  27.2         7.0  3.0  ...
1                 28           27  2437.0  27.1         2.0  0.0  ...
2                 27           25  2177.0  24.2        14.0  3.0  ...
3                 23           23  2070.0  23.0         0.0  0.0  ...
4                 24           24  2005.0  22.3         9.0  7.0  ...

  Per 90 Minutes                                                       \
             Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0           0.11  0.37  0.26   0.37  0.04  0.08   0.13  0.04     0.13
1           0.00  0.07  0.07   0.07  0.11  0.01   0.12  0.11     0.12
2           0.12  0.70  0.45   0.58  0.79  0.14   0.93  0.60     0.74
3           0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.00     0.00
4           0.31  0.72  0.36   0.67  0.32  0.18   0.50  0.24     0.42

  Unnamed: 33_level_0
              Matches
0             Matches
1             Matches
2             Matches
3             Matches
4             Matches

[5 rows x 34 columns]

In [3]:
import os

# Get the current working directory (inside notebooks folder)
current_dir = os.getcwd()

# Navigate up to the main folder and then to the data folder
main_folder = os.path.dirname(current_dir)
data_folder = os.path.join(main_folder, "data")

# Ensure the data folder exists
os.makedirs(data_folder, exist_ok=True)

# Define the JSON file path
json_file_path = os.path.join(data_folder, "real_madrid_stats.json")

# Save the DataFrame as a JSON file
player_stats_df.to_json(json_file_path, orient="records", lines=True)

print(f"DataFrame has been saved to {json_file_path}")

DataFrame has been saved to c:\Users\mehra\Clones\LHL-Final-Project\data\real_madrid_stats.json

In [4]:
import json

# Define the path to the data folder from the notebooks folder
data_folder = os.path.join(os.pardir, "data")  # Navigate to parent folder and then into "data"
file_name = "Real_Madrid_players_market_value.json"
file_path = os.path.join(data_folder, file_name)

# Load the JSON file
with open(file_path, 'r') as file:
    market_value_data = json.load(file)

# Create a DataFrame from the JSON file
market_value_df = pd.json_normalize(market_value_data, record_path=['players'])

# Display the first few rows of the DataFrame to verify
print(market_value_df.head())

    #                          Player  Date of birth/Age Height   Foot  \
0   1  [Thibaut Courtois, Goalkeeper]  May 11, 1992 (32)  2,00m   left
1  13      [Andriy Lunin, Goalkeeper]  Feb 11, 1999 (25)  1,91m  right
2   3     [Éder Militão, Centre-Back]  Jan 18, 1998 (26)  1,86m  right
3  22  [Antonio Rüdiger, Centre-Back]   Mar 3, 1993 (31)  1,90m  right
4   4      [David Alaba, Centre-Back]  Jun 24, 1992 (32)  1,80m   left

        Joined    Signed from      Contract Market value  \
0  Aug 9, 2018     Chelsea FC  Jun 30, 2026      €25.00m
1  Jul 1, 2018  Zorya Lugansk  Jun 30, 2030      €20.00m
2  Jul 1, 2019       FC Porto  Jun 30, 2028      €40.00m
3  Jul 1, 2022     Chelsea FC  Jun 30, 2026      €24.00m
4  Jul 1, 2021  Bayern Munich  Jun 30, 2026      €10.00m

                      Nat.
0                  Belgium
1                  Ukraine
2          [Brazil, Spain]
3  [Germany, Sierra Leone]
4                  Austria

In [5]:
# Display the columns of player_stats_df
player_stats_df_columns = player_stats_df.columns
print(player_stats_df_columns.tolist())

[('Unnamed: 0_level_0', 'Player'), ('Unnamed: 1_level_0', 'Nation'), ('Unnamed: 2_level_0', 'Pos'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Expected', 'xG'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'npxG+xAG'), ('Progression', 'PrgC'), ('Progression', 'PrgP'), ('Progression', 'PrgR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK'), ('Per 90 Minutes', 'xG'), ('Per 90 Minutes', 'xAG'), ('Per 90 Minutes', 'xG+xAG'), ('Per 90 Minutes', 'npxG'), ('Per 90 Minutes', 'npxG+xAG'), ('Unnamed: 33_level_0', 'Matches')]

In [6]:
# Rename and clean columns
player_stats_df.columns = [
    'Player', 'Nation', 'Position', 'Age', 'Matches_Played', 'Starts', 
    'Minutes_Played', '90s_Played', 'Goals', 'Assists', 'Goal_Contributions',
    'Non_Penalty_Goals', 'Penalty_Goals', 'Penalty_Attempts', 'Yellow_Cards', 
    'Red_Cards', 'Expected_Goals', 'Non_Penalty_xG', 'Expected_Assists', 
    'npxG_plus_xA', 'Progressive_Carries', 'Progressive_Passes', 
    'Progressive_Runs', 'Per90_Goals', 'Per90_Assists', 'Per90_Goal_Contributions',
    'Per90_Non_Penalty_Goals', 'Per90_Non_Penalty_Goal_Contributions', 
    'Per90_xG', 'Per90_xA', 'Per90_xG_plus_xA', 'Per90_Non_Penalty_xG', 
    'Per90_Non_Penalty_xG_plus_xA', 'Matches'
]

# Drop unnecessary columns (e.g., 'Matches' if redundant)
player_stats_df.drop(columns=['Matches', 'Per90_xG_plus_xA','Per90_Non_Penalty_xG', 'Per90_Non_Penalty_xG_plus_xA','Per90_Goal_Contributions', 'Per90_Non_Penalty_Goals', 'Per90_Non_Penalty_Goal_Contributions'], inplace=True)

# Display the cleaned DataFrame columns
print(player_stats_df.columns.tolist())

['Player', 'Nation', 'Position', 'Age', 'Matches_Played', 'Starts', 'Minutes_Played', '90s_Played', 'Goals', 'Assists', 'Goal_Contributions', 'Non_Penalty_Goals', 'Penalty_Goals', 'Penalty_Attempts', 'Yellow_Cards', 'Red_Cards', 'Expected_Goals', 'Non_Penalty_xG', 'Expected_Assists', 'npxG_plus_xA', 'Progressive_Carries', 'Progressive_Passes', 'Progressive_Runs', 'Per90_Goals', 'Per90_Assists', 'Per90_xG', 'Per90_xA']

In [7]:
print(player_stats_df.columns)
print(f"Number of columns: {len(player_stats_df.columns)}")

Index(['Player', 'Nation', 'Position', 'Age', 'Matches_Played', 'Starts',
       'Minutes_Played', '90s_Played', 'Goals', 'Assists',
       'Goal_Contributions', 'Non_Penalty_Goals', 'Penalty_Goals',
       'Penalty_Attempts', 'Yellow_Cards', 'Red_Cards', 'Expected_Goals',
       'Non_Penalty_xG', 'Expected_Assists', 'npxG_plus_xA',
       'Progressive_Carries', 'Progressive_Passes', 'Progressive_Runs',
       'Per90_Goals', 'Per90_Assists', 'Per90_xG', 'Per90_xA'],
      dtype='object')
Number of columns: 27

In [8]:
# Drop columns not needed for analysis
columns_to_drop = ['npxG_plus_xA', 'Non_Penalty_xG']
player_stats_df.drop(columns=columns_to_drop, inplace=True)

# Display the updated DataFrame
print(player_stats_df.columns.tolist())

['Player', 'Nation', 'Position', 'Age', 'Matches_Played', 'Starts', 'Minutes_Played', '90s_Played', 'Goals', 'Assists', 'Goal_Contributions', 'Non_Penalty_Goals', 'Penalty_Goals', 'Penalty_Attempts', 'Yellow_Cards', 'Red_Cards', 'Expected_Goals', 'Expected_Assists', 'Progressive_Carries', 'Progressive_Passes', 'Progressive_Runs', 'Per90_Goals', 'Per90_Assists', 'Per90_xG', 'Per90_xA']

In [9]:
print(player_stats_df.columns)
print(f"Number of columns: {len(player_stats_df.columns)}")

Index(['Player', 'Nation', 'Position', 'Age', 'Matches_Played', 'Starts',
       'Minutes_Played', '90s_Played', 'Goals', 'Assists',
       'Goal_Contributions', 'Non_Penalty_Goals', 'Penalty_Goals',
       'Penalty_Attempts', 'Yellow_Cards', 'Red_Cards', 'Expected_Goals',
       'Expected_Assists', 'Progressive_Carries', 'Progressive_Passes',
       'Progressive_Runs', 'Per90_Goals', 'Per90_Assists', 'Per90_xG',
       'Per90_xA'],
      dtype='object')
Number of columns: 25

In [10]:
print(market_value_df.columns.tolist())

['#', 'Player', 'Date of birth/Age', 'Height', 'Foot', 'Joined', 'Signed from', 'Contract', 'Market value', 'Nat.']

In [11]:
market_value_df['Player_Name'] = market_value_df['Player'].apply(
    lambda x: x[0] if isinstance(x, list) else x
).str.strip()

In [12]:
print(market_value_df[['Player', 'Player_Name']].head())

                           Player       Player_Name
0  [Thibaut Courtois, Goalkeeper]  Thibaut Courtois
1      [Andriy Lunin, Goalkeeper]      Andriy Lunin
2     [Éder Militão, Centre-Back]      Éder Militão
3  [Antonio Rüdiger, Centre-Back]   Antonio Rüdiger
4      [David Alaba, Centre-Back]       David Alaba

In [13]:
# Merging player_stats_df and market_value_df dataframes
merged_df = pd.merge(player_stats_df, market_value_df, left_on='Player', right_on='Player_Name', how='inner')

# Display the first few rows of the merged DataFrame
print(merged_df.head())

            Player_x   Nation Position     Age  Matches_Played  Starts  \
0  Federico Valverde   uy URU    MF,DF  26-178              29      29
1    Antonio Rüdiger   de GER       DF  31-319              28      27
2      Kylian Mbappé   fr FRA       FW  26-027              27      25
3   Thibaut Courtois   be BEL       GK  32-250              23      23
4    Jude Bellingham  eng ENG       MF  21-201              24      24

   Minutes_Played  90s_Played  Goals  Assists  ...  \
0          2444.0        27.2    7.0      3.0  ...
1          2437.0        27.1    2.0      0.0  ...
2          2177.0        24.2   14.0      3.0  ...
3          2070.0        23.0    0.0      0.0  ...
4          2005.0        22.3    9.0      7.0  ...

                                Player_y  Date of birth/Age  Height   Foot  \
0  [Federico Valverde, Central Midfield]  Jul 22, 1998 (26)   1,82m  right
1         [Antonio Rüdiger, Centre-Back]   Mar 3, 1993 (31)   1,90m  right
2        [Kylian Mbappé, Centre-Forward]  Dec 20, 1998 (26)   1,78m  right
3         [Thibaut Courtois, Goalkeeper]  May 11, 1992 (32)   2,00m   left
4  [Jude Bellingham, Attacking Midfield]  Jun 29, 2003 (21)   1,86m  right

        Joined           Signed from      Contract  Market value  \
0  Jul 1, 2018  Real Madrid Castilla  Jun 30, 2029      €130.00m
1  Jul 1, 2022            Chelsea FC  Jun 30, 2026       €24.00m
2  Jul 1, 2024   Paris Saint-Germain  Jun 30, 2029      €160.00m
3  Aug 9, 2018            Chelsea FC  Jun 30, 2026       €25.00m
4  Jul 1, 2023     Borussia Dortmund  Jun 30, 2029      €180.00m

                      Nat.        Player_Name
0         [Uruguay, Spain]  Federico Valverde
1  [Germany, Sierra Leone]    Antonio Rüdiger
2       [France, Cameroon]      Kylian Mbappé
3                  Belgium   Thibaut Courtois
4       [England, Ireland]    Jude Bellingham

[5 rows x 36 columns]

In [14]:
# Drop unnecessary columns
columns_to_drop = ['Player_y', 'Age', 'Signed from', 'Joined', 'Nation', 'Player_Name']
merged_df_cleaned = merged_df.drop(columns=columns_to_drop)

# Rename Player_x to Player for simplicity
merged_df_cleaned.rename(columns={'Player_x': 'Player'}, inplace=True)

In [15]:
merged_df_cleaned

,Player,Position,Matches_Played,Starts,Minutes_Played,90s_Played,Goals,Assists,Goal_Contributions,Non_Penalty_Goals,...,Per90_Assists,Per90_xG,Per90_xA,#,Date of birth/Age,Height,Foot,Contract,Market value,Nat.
0,Federico Valverde,"MF,DF",29,29,2444.0,27.2,7.0,3.0,10.0,7.0,...,0.11,0.04,0.08,8,"Jul 22, 1998 (26)","1,82m",right,"Jun 30, 2029",€130.00m,"[Uruguay, Spain]"
1,Antonio Rüdiger,DF,28,27,2437.0,27.1,2.0,0.0,2.0,2.0,...,0.00,0.11,0.01,22,"Mar 3, 1993 (31)","1,90m",right,"Jun 30, 2026",€24.00m,"[Germany, Sierra Leone]"
2,Kylian Mbappé,FW,27,25,2177.0,24.2,14.0,3.0,17.0,11.0,...,0.12,0.79,0.14,9,"Dec 20, 1998 (26)","1,78m",right,"Jun 30, 2029",€160.00m,"[France, Cameroon]"
3,Thibaut Courtois,GK,23,23,2070.0,23.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,1,"May 11, 1992 (32)","2,00m",left,"Jun 30, 2026",€25.00m,Belgium
4,Jude Bellingham,MF,24,24,2005.0,22.3,9.0,7.0,16.0,8.0,...,0.31,0.32,0.18,5,"Jun 29, 2003 (21)","1,86m",right,"Jun 30, 2029",€180.00m,"[England, Ireland]"
5,Aurélien Tchouaméni,"MF,DF",23,22,1781.0,19.8,0.0,0.0,0.0,0.0,...,0.00,0.06,0.03,14,"Jan 27, 2000 (24)","1,88m",right,"Jun 30, 2028",€80.00m,"[France, Cameroon]"
6,Rodrygo,"FW,MF",23,17,1529.0,17.0,7.0,4.0,11.0,7.0,...,0.24,0.21,0.15,11,"Jan 9, 2001 (24)","1,74m",right,"Jun 30, 2028",€100.00m,"[Brazil, Spain]"
7,Lucas Vázquez,DF,25,17,1491.0,16.6,2.0,3.0,5.0,2.0,...,0.18,0.06,0.13,17,"Jul 1, 1991 (33)","1,73m",right,"Jun 30, 2025",€3.50m,Spain
8,Ferland Mendy,DF,20,18,1438.0,16.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,23,"Jun 8, 1995 (29)","1,80m",left,"Jun 30, 2025",€18.00m,"[France, Senegal]"
9,Éder Militão,DF,17,15,1309.0,14.5,1.0,1.0,2.0,1.0,...,0.07,0.06,0.05,3,"Jan 18, 1998 (26)","1,86m",right,"Jun 30, 2028",€40.00m,"[Brazil, Spain]"
10,Brahim Díaz,"FW,MF",21,9,915.0,10.2,2.0,4.0,6.0,2.0,...,0.39,0.24,0.32,21,"Aug 3, 1999 (25)","1,70m",both,"Jun 30, 2027",€35.00m,"[Morocco, Spain]"
11,Eduardo Camavinga,MF,15,11,904.0,10.0,1.0,2.0,3.0,1.0,...,0.20,0.02,0.10,6,"Nov 10, 2002 (22)","1,82m",left,"Jun 30, 2029",€80.00m,"[France, Congo]"
12,Arda Güler,MF,21,8,769.0,8.5,3.0,3.0,6.0,3.0,...,0.35,0.29,0.29,15,"Feb 25, 2005 (19)","1,75m",left,"Jun 30, 2029",€45.00m,Türkiye
13,Dani Ceballos,MF,18,7,761.0,8.5,0.0,0.0,0.0,0.0,...,0.00,0.03,0.06,19,"Aug 7, 1996 (28)","1,79m",right,"Jun 30, 2027",€4.00m,Spain
14,Raúl Asencio,DF,12,5,618.0,6.9,0.0,1.0,1.0,0.0,...,0.15,0.00,0.09,35,"Feb 13, 2003 (21)","1,84m",right,"Jun 30, 2026",€7.50m,Spain
15,Andriy Lunin,GK,6,6,540.0,6.0,0.0,1.0,1.0,0.0,...,0.17,0.00,0.19,13,"Feb 11, 1999 (25)","1,91m",right,"Jun 30, 2030",€20.00m,Ukraine
16,Endrick,FW,16,2,260.0,2.9,2.0,0.0,2.0,2.0,...,0.00,0.67,0.23,16,"Jul 21, 2006 (18)","1,73m",left,"Jun 30, 2030",€40.00m,Brazil
17,Jesús Vallejo,DF,1,0,11.0,0.1,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,18,"Jan 5, 1997 (28)","1,84m",right,"Jun 30, 2025",€1.00m,Spain
18,David Alaba,"DF,MF",0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,"Jun 24, 1992 (32)","1,80m",left,"Jun 30, 2026",€10.00m,Austria

In [16]:
# Check if there are any NaN values in each column
nan_columns = merged_df_cleaned.isnull().any()
print(nan_columns)

Player                 False
Position               False
Matches_Played         False
Starts                 False
Minutes_Played          True
90s_Played              True
Goals                   True
Assists                 True
Goal_Contributions      True
Non_Penalty_Goals       True
Penalty_Goals           True
Penalty_Attempts        True
Yellow_Cards            True
Red_Cards               True
Expected_Goals          True
Expected_Assists        True
Progressive_Carries     True
Progressive_Passes      True
Progressive_Runs        True
Per90_Goals             True
Per90_Assists           True
Per90_xG                True
Per90_xA                True
#                      False
Date of birth/Age      False
Height                 False
Foot                   False
Contract               False
Market value           False
Nat.                   False
dtype: bool

In [17]:
# Replace NaN values with 0 in the entire DataFrame
merged_df_cleaned.fillna(0, inplace=True)

# Confirm there are no NaN values left
print("NaN values handled successfully. Any NaN remaining?")
print(merged_df_cleaned.isnull().any().any())  # This should return False

NaN values handled successfully. Any NaN remaining?
False

In [18]:
# Define the path to the data folder
data_folder_path = os.path.join(os.pardir, "data")
cleaned_file_name = "merged_player_stats_market_value.csv"
cleaned_file_path = os.path.join(data_folder_path, cleaned_file_name)

# Save the cleaned DataFrame as a CSV file in the data folder
merged_df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"The cleaned CSV file has been successfully saved at: {cleaned_file_path}")

The cleaned CSV file has been successfully saved at: ..\data\merged_player_stats_market_value.csv

In [19]:
merged_df_cleaned

,Player,Position,Matches_Played,Starts,Minutes_Played,90s_Played,Goals,Assists,Goal_Contributions,Non_Penalty_Goals,...,Per90_Assists,Per90_xG,Per90_xA,#,Date of birth/Age,Height,Foot,Contract,Market value,Nat.
0,Federico Valverde,"MF,DF",29,29,2444.0,27.2,7.0,3.0,10.0,7.0,...,0.11,0.04,0.08,8,"Jul 22, 1998 (26)","1,82m",right,"Jun 30, 2029",€130.00m,"[Uruguay, Spain]"
1,Antonio Rüdiger,DF,28,27,2437.0,27.1,2.0,0.0,2.0,2.0,...,0.00,0.11,0.01,22,"Mar 3, 1993 (31)","1,90m",right,"Jun 30, 2026",€24.00m,"[Germany, Sierra Leone]"
2,Kylian Mbappé,FW,27,25,2177.0,24.2,14.0,3.0,17.0,11.0,...,0.12,0.79,0.14,9,"Dec 20, 1998 (26)","1,78m",right,"Jun 30, 2029",€160.00m,"[France, Cameroon]"
3,Thibaut Courtois,GK,23,23,2070.0,23.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,1,"May 11, 1992 (32)","2,00m",left,"Jun 30, 2026",€25.00m,Belgium
4,Jude Bellingham,MF,24,24,2005.0,22.3,9.0,7.0,16.0,8.0,...,0.31,0.32,0.18,5,"Jun 29, 2003 (21)","1,86m",right,"Jun 30, 2029",€180.00m,"[England, Ireland]"
5,Aurélien Tchouaméni,"MF,DF",23,22,1781.0,19.8,0.0,0.0,0.0,0.0,...,0.00,0.06,0.03,14,"Jan 27, 2000 (24)","1,88m",right,"Jun 30, 2028",€80.00m,"[France, Cameroon]"
6,Rodrygo,"FW,MF",23,17,1529.0,17.0,7.0,4.0,11.0,7.0,...,0.24,0.21,0.15,11,"Jan 9, 2001 (24)","1,74m",right,"Jun 30, 2028",€100.00m,"[Brazil, Spain]"
7,Lucas Vázquez,DF,25,17,1491.0,16.6,2.0,3.0,5.0,2.0,...,0.18,0.06,0.13,17,"Jul 1, 1991 (33)","1,73m",right,"Jun 30, 2025",€3.50m,Spain
8,Ferland Mendy,DF,20,18,1438.0,16.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,23,"Jun 8, 1995 (29)","1,80m",left,"Jun 30, 2025",€18.00m,"[France, Senegal]"
9,Éder Militão,DF,17,15,1309.0,14.5,1.0,1.0,2.0,1.0,...,0.07,0.06,0.05,3,"Jan 18, 1998 (26)","1,86m",right,"Jun 30, 2028",€40.00m,"[Brazil, Spain]"
10,Brahim Díaz,"FW,MF",21,9,915.0,10.2,2.0,4.0,6.0,2.0,...,0.39,0.24,0.32,21,"Aug 3, 1999 (25)","1,70m",both,"Jun 30, 2027",€35.00m,"[Morocco, Spain]"
11,Eduardo Camavinga,MF,15,11,904.0,10.0,1.0,2.0,3.0,1.0,...,0.20,0.02,0.10,6,"Nov 10, 2002 (22)","1,82m",left,"Jun 30, 2029",€80.00m,"[France, Congo]"
12,Arda Güler,MF,21,8,769.0,8.5,3.0,3.0,6.0,3.0,...,0.35,0.29,0.29,15,"Feb 25, 2005 (19)","1,75m",left,"Jun 30, 2029",€45.00m,Türkiye
13,Dani Ceballos,MF,18,7,761.0,8.5,0.0,0.0,0.0,0.0,...,0.00,0.03,0.06,19,"Aug 7, 1996 (28)","1,79m",right,"Jun 30, 2027",€4.00m,Spain
14,Raúl Asencio,DF,12,5,618.0,6.9,0.0,1.0,1.0,0.0,...,0.15,0.00,0.09,35,"Feb 13, 2003 (21)","1,84m",right,"Jun 30, 2026",€7.50m,Spain
15,Andriy Lunin,GK,6,6,540.0,6.0,0.0,1.0,1.0,0.0,...,0.17,0.00,0.19,13,"Feb 11, 1999 (25)","1,91m",right,"Jun 30, 2030",€20.00m,Ukraine
16,Endrick,FW,16,2,260.0,2.9,2.0,0.0,2.0,2.0,...,0.00,0.67,0.23,16,"Jul 21, 2006 (18)","1,73m",left,"Jun 30, 2030",€40.00m,Brazil
17,Jesús Vallejo,DF,1,0,11.0,0.1,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,18,"Jan 5, 1997 (28)","1,84m",right,"Jun 30, 2025",€1.00m,Spain
18,David Alaba,"DF,MF",0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,4,"Jun 24, 1992 (32)","1,80m",left,"Jun 30, 2026",€10.00m,Austria